version: '3.7'
services:
  book-service:
    image: jpop/book-service:latest
    ports:
      - '9092:9092'
    environment:
      - spring.cloud.config.uri=http://localhost:8888
    build:
      context: book-service
      dockerfile: Dockerfile
#    restart: on-failure