version: '3.7'
services:
    elasticsearch:
        image: elasticsearch:7.13.4
        ports:
          - '9200:9200'
        networks:
          - elk
        environment:
          - discovery.type=single-node
          - xpack.security.enabled=false
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        networks:
          - elk
        
          
    logstash:
        image: logstash:7.13.4
        ports:
          - '5000:5000'
        networks:
          - elk        
        volumes:
          - type: bind
            source: ./logstash/config/logstash.yml
            target: /usr/share/logstash/config/logstash.yml
            read_only: true
          - type: bind
            source: ./logstash/pipeline
            target: /usr/share/logstash/pipeline
            read_only: true
          - type: bind
            source: C:/Users/Rupesh_Patil/Downloads/JPOP Workspace/library-mgmt-system/logging-files
            target: /usr/share/logs/
            read_only: true        
        depends_on:
          - elasticsearch
        networks:
          - elk
    kibana:
        image: kibana:7.13.4
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
          - '5601:5601'
        depends_on:
          - elasticsearch          
        networks:
          - elk
          
    zipkin:
        image: openzipkin/zipkin        
        ports:
          - '9411:9411'
    
networks:
    elk:
      driver: bridge